# This is a basic workflow to help you get started with Actions

name: Deploy to Production workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to run this workflow from any other workflow as a reusable workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Sleep for 30 seconds
        run: sleep 30
        
  deploy-to-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      url: 'http://localhost:8090'
    steps:
      - name: Deploy
        run: echo Deploying to production env
      - name: Sleep for 120 seconds
        run: sleep 120
      
